import { useCallback, useEffect, useState } from 'react'
import { api } from '../../api'
import { useDateFormat } from '../../preferences/useDateFormat'
import { useToast } from '../../toast'
import type { FormFolder, FormSubmissionDetail } from '../../types'

export default function FormResponsesPanel() {
  const { formatDate } = useDateFormat()
  const { showApiError } = useToast()
  const [folders, setFolders] = useState<FormFolder[]>([])
  const [selectedFolderId, setSelectedFolderId] = useState<number | null>(null)
  const [submissions, setSubmissions] = useState<FormSubmissionDetail[]>([])
  const [loadingFolders, setLoadingFolders] = useState(true)
  const [loadingSubmissions, setLoadingSubmissions] = useState(false)
  const [expandedId, setExpandedId] = useState<number | null>(null)

  const loadFolders = useCallback(async () => {
    setLoadingFolders(true)
    try {
      const data = await api.getFormFolders('RESPONSE')
      setFolders(data)
      if (data.length > 0 && selectedFolderId == null) {
        setSelectedFolderId(data[0].id)
      }
    } catch (err) {
      showApiError(err, 'No se pudieron cargar las carpetas de respuestas')
      setFolders([])
    } finally {
      setLoadingFolders(false)
    }
  }, [selectedFolderId, showApiError])

  useEffect(() => { loadFolders() }, [loadFolders])

  useEffect(() => {
    if (selectedFolderId == null) {
      setSubmissions([])
      return
    }
    setLoadingSubmissions(true)
    api.getFormSubmissions(selectedFolderId)
      .then(setSubmissions)
      .catch((err) => {
        showApiError(err, 'No se pudieron cargar las respuestas')
        setSubmissions([])
      })
      .finally(() => setLoadingSubmissions(false))
  }, [selectedFolderId, showApiError])

  const selectedFolder = folders.find((folder) => folder.id === selectedFolderId) ?? null

  return (
    <div className="forms-responses-layout">
      <aside className="forms-folder-sidebar card">
        <h3>Carpetas de respuestas</h3>
        <p className="text-muted forms-sidebar-hint">
          Cada formulario crea una carpeta automática. También puedes usar una carpeta compartida al crear el formulario.
        </p>
        {loadingFolders ? (
          <p className="text-muted">Cargando…</p>
        ) : folders.length === 0 ? (
          <p className="text-muted">Aún no hay respuestas.</p>
        ) : (
          <div className="forms-folder-list">
            {folders.map((folder) => (
              <button
                key={folder.id}
                type="button"
                className={`forms-folder-item${selectedFolderId === folder.id ? ' active' : ''}`}
                onClick={() => setSelectedFolderId(folder.id)}
              >
                <span>{folder.name}</span>
                <span className="forms-folder-count">{folder.submissionCount}</span>
              </button>
            ))}
          </div>
        )}
      </aside>

      <section className="forms-responses-main card">
        {!selectedFolder ? (
          <div className="empty-state">Selecciona una carpeta para ver las respuestas.</div>
        ) : (
          <>
            <div className="forms-responses-head">
              <div>
                <h3>{selectedFolder.name}</h3>
                <p className="text-muted">
                  {selectedFolder.submissionCount} respuesta{selectedFolder.submissionCount === 1 ? '' : 's'}
                  {' · '}
                  {selectedFolder.formCount} formulario{selectedFolder.formCount === 1 ? '' : 's'}
                  {selectedFolder.autoGenerated && ' · Automática'}
                </p>
              </div>
            </div>

            {loadingSubmissions ? (
              <p className="text-muted">Cargando respuestas…</p>
            ) : submissions.length === 0 ? (
              <div className="empty-state">Esta carpeta aún no tiene respuestas.</div>
            ) : (
              <div className="forms-submissions-list">
                {submissions.map((submission) => (
                  <div key={submission.id} className="forms-submission-item">
                    <button
                      type="button"
                      className="forms-submission-summary"
                      onClick={() => setExpandedId(expandedId === submission.id ? null : submission.id)}
                      aria-expanded={expandedId === submission.id}
                    >
                      <div>
                        <strong>{submission.formTitle}</strong>
                        <p className="text-muted">
                          {formatDate(submission.createdAt)}
                          {submission.submitterName ? ` · ${submission.submitterName}` : ''}
                          {submission.importedAt ? ' · Importada' : ''}
                        </p>
                      </div>
                      <span className="measurement-history-chevron">{expandedId === submission.id ? '▾' : '▸'}</span>
                    </button>
                    {expandedId === submission.id && (
                      <div className="forms-submission-answers">
                        {Object.entries(submission.answers).map(([key, value]) => (
                          <div key={key} className="forms-submission-answer-row">
                            <span className="forms-submission-answer-key">{key}</span>
                            <span>{String(value)}</span>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            )}
          </>
        )}
      </section>
    </div>
  )
}
