package com.gymplatform.service;

import com.gymplatform.domain.entity.CustomForm;
import com.gymplatform.domain.entity.FormFolder;
import com.gymplatform.domain.entity.Organization;
import com.gymplatform.domain.enums.FormFolderKind;
import com.gymplatform.dto.FormFolderRequest;
import com.gymplatform.dto.FormFolderResponse;
import com.gymplatform.exception.BusinessException;
import com.gymplatform.exception.ResourceNotFoundException;
import com.gymplatform.repository.FormFolderRepository;
import com.gymplatform.repository.OrganizationRepository;
import com.gymplatform.util.SecurityUtils;
import com.gymplatform.util.SlugHelper;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.List;

@Service
public class FormFolderService {

    private final FormFolderRepository folderRepository;
    private final OrganizationRepository organizationRepository;

    public FormFolderService(FormFolderRepository folderRepository, OrganizationRepository organizationRepository) {
        this.folderRepository = folderRepository;
        this.organizationRepository = organizationRepository;
    }

    public List<FormFolderResponse> listFolders(Long organizationId, FormFolderKind kind) {
        requireConfigRole();
        return folderRepository.findByOrganizationIdAndKindOrderByNameAsc(organizationId, kind).stream()
                .map(folder -> toResponse(folder, kind))
                .toList();
    }

    @Transactional
    public FormFolderResponse createFolder(Long organizationId, FormFolderKind kind, FormFolderRequest request) {
        requireConfigRole();
        if (kind == FormFolderKind.RESPONSE && request.name().toLowerCase().contains("autom")) {
            throw new BusinessException("Las carpetas automáticas se crean al guardar un formulario");
        }
        Organization org = organizationRepository.findById(organizationId)
                .orElseThrow(() -> new ResourceNotFoundException("Organización no encontrada"));
        String slug = resolveSlug(organizationId, request.name(), kind);
        FormFolder folder = new FormFolder();
        folder.setOrganization(org);
        folder.setName(request.name().trim());
        folder.setSlug(slug);
        folder.setKind(kind);
        folder.setAutoGenerated(false);
        return toResponse(folderRepository.save(folder), kind);
    }

    @Transactional
    public FormFolder createAutoResponseFolder(CustomForm form) {
        Organization org = form.getOrganization();
        String baseName = form.getTitle().trim() + " — Respuestas";
        String slug = resolveSlug(org.getId(), baseName, FormFolderKind.RESPONSE);
        FormFolder folder = new FormFolder();
        folder.setOrganization(org);
        folder.setName(baseName);
        folder.setSlug(slug);
        folder.setKind(FormFolderKind.RESPONSE);
        folder.setAutoGenerated(true);
        folder.setSourceForm(form);
        return folderRepository.save(folder);
    }

    public FormFolder requireFolder(Long organizationId, Long folderId, FormFolderKind kind) {
        FormFolder folder = folderRepository.findByIdAndOrganizationId(folderId, organizationId)
                .orElseThrow(() -> new ResourceNotFoundException("Carpeta no encontrada"));
        if (folder.getKind() != kind) {
            throw new BusinessException("La carpeta no es del tipo esperado");
        }
        return folder;
    }

    private FormFolderResponse toResponse(FormFolder folder, FormFolderKind kind) {
        long secondaryCount = kind == FormFolderKind.RESPONSE
                ? folderRepository.countDistinctForms(folder.getId())
                : folderRepository.countTemplateForms(folder.getId());
        return new FormFolderResponse(
                folder.getId(),
                folder.getName(),
                folder.getSlug(),
                folder.getKind(),
                folder.isAutoGenerated(),
                folder.getSourceForm() != null ? folder.getSourceForm().getId() : null,
                folderRepository.countSubmissions(folder.getId()),
                secondaryCount,
                folder.getCreatedAt()
        );
    }

    private String resolveSlug(Long organizationId, String name, FormFolderKind kind) {
        String base = SlugHelper.slugify(name);
        String candidate = base;
        int suffix = 2;
        while (folderRepository.existsByOrganizationIdAndSlugAndKind(organizationId, candidate, kind)) {
            candidate = base + "-" + suffix++;
        }
        return candidate;
    }

    private void requireConfigRole() {
        var user = SecurityUtils.currentUser();
        if (!user.hasRole("GYM_OWNER") && !user.hasRole("RECEPTIONIST")) {
            throw new BusinessException("No tienes permiso para gestionar formularios");
        }
    }
}
