package com.gymplatform.domain.entity;

import com.gymplatform.domain.enums.FormFolderKind;
import jakarta.persistence.*;
import java.time.Instant;

@Entity
@Table(
        name = "form_folders",
        uniqueConstraints = @UniqueConstraint(columnNames = {"organization_id", "slug", "kind"})
)
public class FormFolder {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "organization_id", nullable = false)
    private Organization organization;

    @Column(nullable = false, length = 120)
    private String name;

    @Column(nullable = false, length = 120)
    private String slug;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private FormFolderKind kind;

    @Column(nullable = false)
    private boolean autoGenerated = false;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "source_form_id")
    private CustomForm sourceForm;

    @Column(nullable = false, updatable = false)
    private Instant createdAt = Instant.now();

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    public Organization getOrganization() { return organization; }
    public void setOrganization(Organization organization) { this.organization = organization; }
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
    public String getSlug() { return slug; }
    public void setSlug(String slug) { this.slug = slug; }
    public FormFolderKind getKind() { return kind; }
    public void setKind(FormFolderKind kind) { this.kind = kind; }
    public boolean isAutoGenerated() { return autoGenerated; }
    public void setAutoGenerated(boolean autoGenerated) { this.autoGenerated = autoGenerated; }
    public CustomForm getSourceForm() { return sourceForm; }
    public void setSourceForm(CustomForm sourceForm) { this.sourceForm = sourceForm; }
    public Instant getCreatedAt() { return createdAt; }
    public void setCreatedAt(Instant createdAt) { this.createdAt = createdAt; }
}
