package com.gymplatform.dto;

import com.gymplatform.domain.enums.FormFolderKind;
import java.time.Instant;

public record FormFolderResponse(
        Long id,
        String name,
        String slug,
        FormFolderKind kind,
        boolean autoGenerated,
        Long sourceFormId,
        long submissionCount,
        long formCount,
        Instant createdAt
) {}
